version: 0.2
phases:
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - echo "Validating SAM..."
      - sam validate
      - echo "SAM Validated."
      - echo "Building SAM..."
      - sam build
      - echo "SAM Built."
  post_build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - echo "Updating Lambda application..."
      - sam deploy
      - echo "Done"