version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - cd frontend
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip app.py
  post_build:
    commands:
      - echo "Updating Lambda application..."
      - aws lambda update-function-code --function-name sam-dash --zip-file fileb:deployment_package.zip
      - echo "Done"